export const GET_LIST_CONSULTANT = 'GET_LIST_CONSULTANT';
export const GET_LIST_CONSULTANT_SUCCESS = 'GET_LIST_CONSULTANT_SUCCESS';
export const GET_LIST_CONSULTANT_ERROR = 'GET_LIST_CONSULTANT_ERROR';
export const GET_LIST_CONSULTANT_CLEANUP = 'GET_LIST_CONSULTANT_CLEANUP';

export const GET_REMAIN_CONSULTANT = 'GET_REMAIN_CONSULTANT';
export const GET_REMAIN_CONSULTANT_SUCCESS = 'GET_REMAIN_CONSULTANT_SUCCESS';
export const GET_REMAIN_CONSULTANT_ERROR = 'GET_REMAIN_CONSULTANT_ERROR';
export const GET_REMAIN_CONSULTANT_CLEANUP = 'GET_REMAIN_CONSULTANT_CLEANUP';

export const SWITCH_USER_FIND_DATA = 'SWITCH_USER_FIND_DATA';
export const SWITCH_USER_FIND_DATA_SUCCESS = 'SWITCH_USER_FIND_DATA_SUCCESS';
export const SWITCH_USER_FIND_DATA_ERROR = 'SWITCH_USER_FIND_DATA_ERROR';
export const SWITCH_USER_FIND_DATA_CLEANUP = 'SWITCH_USER_FIND_DATA_CLEANUP';

export const GET_CONSULTANT_CALENDAR = 'GET_CONSULTANT_CALENDAR';
export const GET_CONSULTANT_CALENDAR_SUCCESS = 'GET_CONSULTANT_CALENDAR_SUCCESS';
export const GET_CONSULTANT_CALENDAR_ERROR = 'GET_CONSULTANT_CALENDAR_ERROR';
export const GET_CONSULTANT_CALENDAR_CLEANUP = 'GET_CONSULTANT_CALENDAR_CLEANUP';
