export const GET_LIST_SALE_PROCESS = 'GET_LIST_SALE_PROCESS';
export const GET_LIST_SALE_PROCESS_SUCCESS = 'GET_LIST_SALE_PROCESS_SUCCESS';
export const GET_LIST_SALE_PROCESS_ERROR = 'GET_LIST_SALE_PROCESS_ERROR';
export const GET_LIST_SALE_PROCESS_CLEANUP = 'GET_LIST_SALE_PROCESS_CLEANUP';

export const STORE_CUSTOMER_PROCESS = 'STORE_CUSTOMER_PROCESS';
export const STORE_CUSTOMER_PROCESS_SUCCESS = 'STORE_CUSTOMER_PROCESS_SUCCESS';
export const STORE_CUSTOMER_PROCESS_ERROR = 'STORE_CUSTOMER_PROCESS_ERROR';
export const STORE_CUSTOMER_PROCESS_CLEANUP = 'STORE_CUSTOMER_PROCESS_CLEANUP';
