export const GET_LIST_SALE = 'GET_LIST_SALE';
export const GET_LIST_SALE_SUCCESS = 'GET_LIST_SALE_SUCCESS';
export const GET_LIST_SALE_ERROR = 'GET_LIST_SALE_ERROR';
export const GET_LIST_SALE_CLEANUP = 'GET_LIST_SALE_CLEANUP';

export const GET_LIST_SALE2 = 'GET_LIST_SALE2';
export const GET_LIST_SALE2_SUCCESS = 'GET_LIST_SALE2_SUCCESS';
export const GET_LIST_SALE2_ERROR = 'GET_LIST_SALE2_ERROR';
export const GET_LIST_SALE2_CLEANUP = 'GET_LIST_SALE2_CLEANUP';

export const GET_REMAIN_SALE = 'GET_REMAIN_SALE';
export const GET_REMAIN_SALE_SUCCESS = 'GET_REMAIN_SALE_SUCCESS';
export const GET_REMAIN_SALE_ERROR = 'GET_REMAIN_SALE_ERROR';
export const GET_REMAIN_SALE_CLEANUP = 'GET_REMAIN_SALE_CLEANUP';

export const SWITCH_USER_SALE_FIND_DATA = 'SWITCH_USER_SALE_FIND_DATA';
export const SWITCH_USER_SALE_FIND_DATA_SUCCESS = 'SWITCH_USER_SALE_FIND_DATA_SUCCESS';
export const SWITCH_USER_SALE_FIND_DATA_ERROR = 'SWITCH_USER_SALE_FIND_DATA_ERROR';
export const SWITCH_USER_SALE_FIND_DATA_CLEANUP = 'SWITCH_USER_SALE_FIND_DATA_CLEANUP';
