export const GET_LIST = 'GET_LIST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_ERROR = 'GET_LIST_ERROR';
export const GET_LIST_CLEANUP = 'GET_LIST_CLEANUP';

export const GET_DETAIL_CUSTOMER = 'GET_DETAIL_CUSTOMER';
export const GET_DETAIL_CUSTOMER_SUCCESS = 'GET_DETAIL_CUSTOMER_SUCCESS';
export const GET_DETAIL_CUSTOMER_ERROR = 'GET_DETAIL_CUSTOMER_ERROR';
export const GET_DETAIL_CUSTOMER_CLEANUP = 'GET_DETAIL_CUSTOMER_CLEANUP';

export const CREATE_DETAIL_CUSTOMER = 'CREATE_DETAIL_CUSTOMER';
export const CREATE_DETAIL_CUSTOMER_SUCCESS = 'CREATE_DETAIL_CUSTOMER_SUCCESS';
export const CREATE_DETAIL_CUSTOMER_ERROR = 'CREATE_DETAIL_CUSTOMER_ERROR';
export const CREATE_DETAIL_CUSTOMER_CLEANUP = 'CREATE_DETAIL_CUSTOMER_CLEANUP';

export const UPDATE_DETAIL_CUSTOMER = 'UPDATE_DETAIL_CUSTOMER';
export const UPDATE_DETAIL_CUSTOMER_SUCCESS = 'UPDATE_DETAIL_CUSTOMER_SUCCESS';
export const UPDATE_DETAIL_CUSTOMER_ERROR = 'UPDATE_DETAIL_CUSTOMER_ERROR';
export const UPDATE_DETAIL_CUSTOMER_CLEANUP = 'UPDATE_DETAIL_CUSTOMER_CLEANUP';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';
export const DELETE_CUSTOMER_CLEANUP = 'DELETE_CUSTOMER_CLEANUP';

export const GET_DATA_FOR_CREATE_CUSTOMER = 'GET_DATA_FOR_CREATE_CUSTOMER';
export const GET_DATA_FOR_CREATE_CUSTOMER_SUCCESS = 'GET_DATA_FOR_CREATE_CUSTOMER_SUCCESS';
export const GET_DATA_FOR_CREATE_CUSTOMER_ERROR = 'GET_DATA_FOR_CREATE_CUSTOMER_ERROR';
export const GET_DATA_FOR_CREATE_CUSTOMER_CLEANUP = 'GET_DATA_FOR_CREATE_CUSTOMER_CLEANUP';

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const CREATE_CUSTOMER_CLEANUP = 'CREATE_CUSTOMER_CLEANUP';

export const UPLOAD_CUSTOMER = 'UPLOAD_CUSTOMER';
export const UPLOAD_CUSTOMER_SUCCESS = 'UPLOAD_CUSTOMER_SUCCESS';
export const UPLOAD_CUSTOMER_ERROR = 'UPLOAD_CUSTOMER_ERROR';
export const UPLOAD_CUSTOMER_CLEANUP = 'UPLOAD_CUSTOMER_CLEANUP';

export const DOWNLOAD_CUSTOMER_EXCEL = 'DOWNLOAD_CUSTOMER_EXCEL';
export const DOWNLOAD_CUSTOMER_EXCEL_SUCCESS = 'DOWNLOAD_CUSTOMER_EXCEL_SUCCESS';
export const DOWNLOAD_CUSTOMER_EXCEL_ERROR = 'DOWNLOAD_CUSTOMER_EXCEL_ERROR';
export const DOWNLOAD_CUSTOMER_EXCEL_CLEANUP = 'DOWNLOAD_CUSTOMER_EXCEL_CLEANUP';

export const SAVE_CUSTOMER_EXCEL = 'SAVE_CUSTOMER_EXCEL';
export const SAVE_CUSTOMER_EXCEL_SUCCESS = 'SAVE_CUSTOMER_EXCEL_SUCCESS';
export const SAVE_CUSTOMER_EXCEL_ERROR = 'SAVE_CUSTOMER_EXCEL_ERROR';
export const SAVE_CUSTOMER_EXCEL_CLEANUP = 'SAVE_CUSTOMER_EXCEL_CLEANUP';

export const CREATE_CUSTOMER_LOG = 'CREATE_CUSTOMER_LOG';
export const CREATE_CUSTOMER_LOG_SUCCESS = 'CREATE_CUSTOMER_LOG_SUCCESS';
export const CREATE_CUSTOMER_LOG_ERROR = 'CREATE_CUSTOMER_LOG_ERROR';
export const CREATE_CUSTOMER_LOG_CLEANUP = 'CREATE_CUSTOMER_LOG_CLEANUP';

export const CREATE_CUSTOMER_SCHEDULE = 'CREATE_CUSTOMER_SCHEDULE';
export const CREATE_CUSTOMER_SCHEDULE_SUCCESS = 'CREATE_CUSTOMER_SCHEDULE_SUCCESS';
export const CREATE_CUSTOMER_SCHEDULE_ERROR = 'CREATE_CUSTOMER_SCHEDULE_ERROR';
export const CREATE_CUSTOMER_SCHEDULE_CLEANUP = 'CREATE_CUSTOMER_SCHEDULE_CLEANUP';
