export const GET_LIST_BRANCH = 'GET_LIST_BRANCH';
export const GET_LIST_SUCCESS_BRANCH = 'GET_LIST_SUCCESS_BRANCH';
export const GET_LIST_ERROR_BRANCH = 'GET_LIST_ERROR_BRANCH';
export const GET_LIST_CLEANUP_BRANCH = 'GET_LIST_CLEANUP_BRANCH';

export const CREATE_BRANCH = "CREATE_BRANCH";
export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const CREATE_BRANCH_ERROR = "CREATE_BRANCH_ERROR";
export const CREATE_BRANCH_CLEANUP = "CREATE_BRANCH_CLEANUP";