export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_ERROR = "GET_LIST_ERROR";
export const GET_LIST_CLEANUP = "GET_LIST_CLEANUP";

export const GET_DETAIL_USER = "GET_DETAIL_USER";
export const GET_DETAIL_USER_SUCCESS = "GET_DETAIL_USER_SUCCESS";
export const GET_DETAIL_USER_ERROR = "GET_DETAIL_USER_ERROR";
export const GET_DETAIL_USER_CLEANUP = "GET_DETAIL_USER_CLEANUP";

export const CREATE_DETAIL_USER = "CREATE_DETAIL_USER";
export const CREATE_DETAIL_USER_SUCCESS = "CREATE_DETAIL_USER_SUCCESS";
export const CREATE_DETAIL_USER_ERROR = "CREATE_DETAIL_USER_ERROR";
export const CREATE_DETAIL_USER_CLEANUP = "CREATE_DETAIL_USER_CLEANUP";

export const UPDATE_DETAIL_USER = "UPDATE_DETAIL_USER";
export const UPDATE_DETAIL_USER_SUCCESS = "UPDATE_DETAIL_USER_SUCCESS";
export const UPDATE_DETAIL_USER_ERROR = "UPDATE_DETAIL_USER_ERROR";
export const UPDATE_DETAIL_USER_CLEANUP = "UPDATE_DETAIL_USER_CLEANUP";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const DELETE_USER_CLEANUP = "DELETE_USER_CLEANUP";

export const GET_DATA_FOR_CREATE_USER = "GET_DATA_FOR_CREATE_USER";
export const GET_DATA_FOR_CREATE_USER_SUCCESS =
  "GET_DATA_FOR_CREATE_USER_SUCCESS";
export const GET_DATA_FOR_CREATE_USER_ERROR =
  "GET_DATA_FOR_CREATE_USER_ERROR";
export const GET_DATA_FOR_CREATE_USER_CLEANUP =
  "GET_DATA_FOR_CREATE_USER_CLEANUP";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";
export const CREATE_USER_CLEANUP = "CREATE_USER_CLEANUP";
