export const GET_LIST_PROCESS = "GET_LIST_PROCESS";
export const GET_LIST_SUCCESS_PROCESS = "GET_LIST_SUCCESS_PROCESS";
export const GET_LIST_ERROR_PROCESS = "GET_LIST_ERROR_PROCESS";
export const GET_LIST_CLEANUP_PROCESS = "GET_LIST_CLEANUP_PROCESS";

export const CREATE_PROCESS = "CREATE_PROCESS";
export const CREATE_PROCESS_SUCCESS = "CREATE_PROCESS_SUCCESS";
export const CREATE_PROCESS_ERROR = "CREATE_PROCESS_ERROR";
export const CREATE_PROCESS_CLEANUP = "CREATE_PROCESS_CLEANUP";

export const EDIT_PROCESS = 'EDIT_PROCESS';
export const EDIT_PROCESS_SUCCESS = 'EDIT_PROCESS_SUCCESS';
export const EDIT_PROCESS_ERROR = 'EDIT_PROCESS_ERROR';
export const EDIT_PROCESS_CLEANUP = 'EDIT_PROCESS_CLEANUP';

export const DELETE_PROCESS = 'DELETE_PROCESS';
export const DELETE_PROCESS_SUCCESS = 'DELETE_PROCESS_SUCCESS';
export const DELETE_PROCESS_ERROR = 'DELETE_PROCESS_ERROR';
export const DELETE_PROCESS_CLEANUP = 'DELETE_PROCESS_CLEANUP';

// Market
export const GET_LIST_MARKET = "GET_LIST_MARKET";
export const GET_LIST_MARKET_SUCCESS = "GET_LIST_MARKET_SUCCESS";
export const GET_LIST_MARKET_ERROR = "GET_LIST_MARKET_ERROR";
export const GET_LIST_MARKET_CLEANUP = "GET_LIST_MARKET_CLEANUP";

export const CREATE_MARKET = "CREATE_MARKET";
export const CREATE_MARKET_SUCCESS = "CREATE_MARKET_SUCCESS";
export const CREATE_MARKET_ERROR = "CREATE_MARKET_ERROR";
export const CREATE_MARKET_CLEANUP = "CREATE_MARKET_CLEANUP";

export const DELETE_MARKET = 'DELETE_MARKET';
export const DELETE_MARKET_SUCCESS = 'DELETE_MARKET_SUCCESS';
export const DELETE_MARKET_ERROR = 'DELETE_MARKET_ERROR';
export const DELETE_MARKET_CLEANUP = 'DELETE_MARKET_CLEANUP';

export const EDIT_MARKET = 'EDIT_MARKET';
export const EDIT_MARKET_SUCCESS = 'EDIT_MARKET_SUCCESS';
export const EDIT_MARKET_ERROR = 'EDIT_MARKET_ERROR';
export const EDIT_MARKET_CLEANUP = 'EDIT_MARKET_CLEANUP';
