export const GET_LIST_CUSTOMER_TYPE = "GET_LIST_CUSTOMER_TYPE";
export const GET_LIST_SUCCESS_CUSTOMER_TYPE = "GET_LIST_SUCCESS_CUSTOMER_TYPE";
export const GET_LIST_ERROR_CUSTOMER_TYPE = "GET_LIST_ERROR_CUSTOMER_TYPE";
export const GET_LIST_CLEANUP_CUSTOMER_TYPE = "GET_LIST_CLEANUP_CUSTOMER_TYPE";

export const CREATE_CUSTOMER_TYPE = "CREATE_CUSTOMER_TYPE";
export const CREATE_CUSTOMER_TYPE_SUCCESS = "CREATE_CUSTOMER_TYPE_SUCCESS";
export const CREATE_CUSTOMER_TYPE_ERROR = "CREATE_CUSTOMER_TYPE_ERROR";
export const CREATE_CUSTOMER_TYPE_CLEANUP = "CREATE_CUSTOMER_TYPE_CLEANUP";
