export const GET_LIST_CAMPAIGN = "GET_LIST_CAMPAIGN";
export const GET_LIST_CAMPAIGN_SUCCESS = "GET_LIST_CAMPAIGN_SUCCESS";
export const GET_LIST_CAMPAIGN_ERROR = "GET_LIST_CAMPAIGN_ERROR";
export const GET_LIST_CAMPAIGN_CLEANUP = "GET_LIST_CAMPAIGN_CLEANUP";

export const GET_DETAIL_CAMPAIGN = "GET_DETAIL_CAMPAIGN";
export const GET_DETAIL_CAMPAIGN_SUCCESS = "GET_DETAIL_CAMPAIGN_SUCCESS";
export const GET_DETAIL_CAMPAIGN_ERROR = "GET_DETAIL_CAMPAIGN_ERROR";
export const GET_DETAIL_CAMPAIGN_CLEANUP = "GET_DETAIL_CAMPAIGN_CLEANUP";

export const CREATE_DETAIL_CAMPAIGN = "CREATE_DETAIL_CAMPAIGN";
export const CREATE_DETAIL_CAMPAIGN_SUCCESS = "CREATE_DETAIL_CAMPAIGN_SUCCESS";
export const CREATE_DETAIL_CAMPAIGN_ERROR = "CREATE_DETAIL_CAMPAIGN_ERROR";
export const CREATE_DETAIL_CAMPAIGN_CLEANUP = "CREATE_DETAIL_CAMPAIGN_CLEANUP";

export const UPDATE_DETAIL_CAMPAIGN = "UPDATE_DETAIL_CAMPAIGN";
export const UPDATE_DETAIL_CAMPAIGN_SUCCESS = "UPDATE_DETAIL_CAMPAIGN_SUCCESS";
export const UPDATE_DETAIL_CAMPAIGN_ERROR = "UPDATE_DETAIL_CAMPAIGN_ERROR";
export const UPDATE_DETAIL_CAMPAIGN_CLEANUP = "UPDATE_DETAIL_CAMPAIGN_CLEANUP";

export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_ERROR = "DELETE_CAMPAIGN_ERROR";
export const DELETE_CAMPAIGN_CLEANUP = "DELETE_CAMPAIGN_CLEANUP";

export const GET_DATA_FOR_CREATE_CAMPAIGN = "GET_DATA_FOR_CREATE_CAMPAIGN";
export const GET_DATA_FOR_CREATE_CAMPAIGN_SUCCESS =
  "GET_DATA_FOR_CREATE_CAMPAIGN_SUCCESS";
export const GET_DATA_FOR_CREATE_CAMPAIGN_ERROR =
  "GET_DATA_FOR_CREATE_CAMPAIGN_ERROR";
export const GET_DATA_FOR_CREATE_CAMPAIGN_CLEANUP =
  "GET_DATA_FOR_CREATE_CAMPAIGN_CLEANUP";

export const CREATE_CAMPAIGN = "CREATE_CAMPAIGN";
export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_ERROR = "CREATE_CAMPAIGN_ERROR";
export const CREATE_CAMPAIGN_CLEANUP = "CREATE_CAMPAIGN_CLEANUP";
