export const GET_LIST_ROLE = "GET_LIST_ROLE";
export const GET_LIST_SUCCESS_ROLE = "GET_LIST_SUCCESS_ROLE";
export const GET_LIST_ERROR_ROLE = "GET_LIST_ERROR_ROLE";
export const GET_LIST_CLEANUP_ROLE = "GET_LIST_CLEANUP_ROLE";

export const CREATE_ROLE = "CREATE_ROLE";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_ERROR = "CREATE_ROLE_ERROR";
export const CREATE_ROLE_CLEANUP = "CREATE_ROLE_CLEANUP";
